### ISSUE TITLE
Add and fix some commands

### ISSUE THREAD

**Issue by zelenovas** [Userator/deploid#1]
**improve failed validation message**
```
Structure INVALID: 
    directory "/home/zelenov/ATS/test/releases" does not exist
    file "/home/zelenov/ATS/test/deploid.log" does not exist

```

### ADD commands
**check if release exists**
`release:switch releaseName`

**create dirs and files which are not exists**
`structure:repair`

**remove dirs and files which are not in original structure**
`structure:clean`

**remove all dirs and files**
`structure:destroy`

### CHANGE commands:

**should echo current release name**
`release:current`

**remove all releases**
`release:remove *`

**check if arg1 is empty**
`release:remove ""`

**do not ask release name, use unified release name format (e.g. YYYY-MM-DD_hh-mm-ss)**
`release:create`

**Comment by userator** [comment]
decline command "structure:destroy", others implemented
